<?php
// Array to set the user access permission for the particular user to access the mune 
$PermissionArray=array('Masters'=>array(
 'Unit Master'=>array('View'=>'unit_view','Add'=>'unit_add','Edit'=>'unit_edit','Cancel'=>'','Explode'=>''),
 'Group Master'=>array('View'=>'group_view','Add'=>'group_add','Edit'=>'group_edit','Cancel'=>'','Explode'=>''),
 'State Master'=>array('View'=>'state_view','Add'=>'state_add','Edit'=>'state_edit','Cancel'=>'','Explode'=>''),
 'City Master'=>array('View'=>'city_view','Add'=>'city_add','Edit'=>'city_edit','Cancel'=>'','Explode'=>''),
 'Location Master'=>array('View'=>'location_view','Add'=>'location_add','Edit'=>'location_edit','Cancel'=>'','Explode'=>''),
 'Principal Master'=>array('View'=>'principal_view','Add'=>'principal_add','Edit'=>'principal_edit','Cancel'=>'','Explode'=>''),
 'Supplier Master'=>array('View'=>'supplier_view','Add'=>'supplier_add','Edit'=>'supplier_edit','Cancel'=>'','Explode'=>''),
 'Item Master'=>array('View'=>'item_view','Add'=>'item_add','Edit'=>'item_edit','Cancel'=>'','Explode'=>''),
 'Buyer Master'=>array('View'=>'buyer_view','Add'=>'buyer_add','Edit'=>'buyer_edit','Cancel'=>'','Explode'=>''),
 /* BOF to add HSN Master and Tax Master by Ayush Giri on 06-06-2017 */
 'HSN Master'=>array('View'=>'hsn_view','Add'=>'hsn_add','Edit'=>'hsn_edit','Cancel'=>'','Explode'=>''),
 'TAX Master'=>array('View'=>'tax_view','Add'=>'tax_add','Edit'=>'tax_edit','Cancel'=>'','Explode'=>'')),
 /* BOF to add HSN Master and Tax Master by Ayush Giri on 06-06-2017 */
 'Orders\'s'=>array(
 'Challan'=>array('View'=>'challan_view','Add'=>'challan_add','Edit'=>'challan_edit','Cancel'=>'','Explode'=>''),
 'Quotation'=>array('View'=>'quotation_view','Add'=>'quotation_add','Edit'=>'quotation_edit','Cancel'=>'','Explode'=>''),
 'Purchase Order'=>array('View'=>'po_view','Add'=>'po_add','Edit'=>'po_edit','Cancel'=>'','Explode'=>''),
'Recurring Purchase Order'=>array('View'=>'recurringpo_View','Add'=>'recurringpo_add','Edit'=>'recurringpo_edit','Cancel'=>'','Explode'=>''),
'Management Approval'=>array('View'=>'mngapproval_View','Add'=>'mngapproval_add','Edit'=>'','Cancel'=>'','Explode'=>''),
 'Stock Transfer'=>array('View'=>'stock_transfer_view','Add'=>'stock_transfer_add','Edit'=>'stock_transfer_edit','Cancel'=>'','Explode'=>''),
 'Stock Check'=>array('View'=>'stock_check_view','Add'=>'stock_check_add','Edit'=>'stock_check_edit','Cancel'=>'','Explode'=>''),
 'Pending Purchase Order'=>array('View'=>'pendingpo_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
 'Purchase Order Partial Delivered'=>array('View'=>'partialpo_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
 'Purchase Order Delivered'=>array('View'=>'deliveredpo_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>'')),
'Invoice'=>array(
 'In-Coming Excise'=>array('View'=>'inexcise_view','Add'=>'inexcise_add','Edit'=>'inexcise_edit','Cancel'=>'inexcise_cancel','Explode'=>''),
 'In-Coming Non Excise'=>array('View'=>'innonexcise_view','Add'=>'innonexcise_add','Edit'=>'innonexcise_edit','Cancel'=>'innonexcise_cancel','Explode'=>''),
 'Out-Going Excise'=>array('View'=>'outexcise_view','Add'=>'outexcise_add','Edit'=>'outexcise_edit','Cancel'=>'outexcise_cancel','Explode'=>''),
 'Out-Going Non Excise'=>array('View'=>'outnonexcise_view','Add'=>'outnonexcise_add','Edit'=>'outnonexcise_edit','Cancel'=>'outnonexcise_cancel','Explode'=>''),
 'Make Payment'=>array('View'=>'payment_view','Add'=>'payment_add','Edit'=>'','Cancel'=>'payment_cancel','Explode'=>''),
 'Payment pending Invoice List'=>array('View'=>'pendinginv_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
 'Payment pending Buyer List'=>array('View'=>'pendingbuyer_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),),
'Revenue'=>array('Financial Year Wise Revenue Detail'=>array('View'=>'finrevenue_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Buyer Wise Revenue Detail'=>array('View'=>'buyerrevenue_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>'')),
'Reports'=>array(
 'Excise Stock Statement With Value'=>array('View'=>'excisestockval_View','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
 'NonExcise Stock Statement With Value'=>array('View'=>'nonexcisestockval_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Excise NonExcise Challan Stock Statement'=>array('View'=>'excisenonexcixestoc_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Excise Stock Statement'=>array('View'=>'excisestockstmt_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Non Excise Stock Statement'=>array('View'=>'nonexcisestockstmt_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Excise Secondary Sales Statement'=>array('View'=>'excisesecondsal_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Non Excise Secondary Sales Statement'=>array('View'=>'nonexcisesecondsal_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Excise Sales Statement'=>array('View'=>'excisesalstmt_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Non Excise Sales Statement'=>array('View'=>'nonexcisesalstmt_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Excise Product Ledger'=>array('View'=>'exciseproductledger_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Non Excise Product Ledger'=>array('View'=>'nonexciseproductledger_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Sales Tax Return Excise'=>array('View'=>'salestaxreturnexcise_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Sales Tax Return Non Excise'=>array('View'=>'salestaxreturnnonexcise_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Incoming Excise Return'=>array('View'=>'inexcisereturn_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Incoming Non Excise Return'=>array('View'=>'innonexcisereturn_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Margin Report'=>array('View'=>'marginreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Purchase Report'=>array('View'=>'purchasereport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Daily Sales Report'=>array('View'=>'dailysalesreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Sales Tally Report'=>array('View'=>'salestallyreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Chalan Report'=>array('View'=>'chalanreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Quotation Report'=>array('View'=>'quotationreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>''),
'Rg 23D Report'=>array('View'=>'rg23dreport_view','Add'=>'','Edit'=>'','Cancel'=>'','Explode'=>'')),

'Manage Users'=>array(
'User Master'=>array('View'=>'user_view','Add'=>'user_add','Edit'=>'user_edit','Cancel'=>'','Explode'=>''),
'Add Privilege'=>array('View'=>'privilege_view','Add'=>'privilege_add','Edit'=>'challanEdit','Cancel'=>'','Explode'=>''),
'Group Permission'=>array('View'=>'groupperm_view','Add'=>'groupperm_add','Edit'=>'groupperm_adit','Cancel'=>'','Explode'=>'')));
?>
